### ISSUE TITLE
"Go back to categories" button causes over-scroll

### ISSUE THREAD

**Issue by EverettBerry** [kirbyk/donger-board#23]
Certain categories, like "dongers" and "upset" which have scroll widths longer than the scroll width of the main categories layout cause the keyboard to freak out. To see this in action check out the video below:

https://www.youtube.com/watch?v=dfp0-N-La14

**Comment by nlarew** [comment]
Turning animated to false on scrollView.scrollRectToVisible fixes this

**Comment by EverettBerry** [comment]
Fixed in def798d21ebb720754f4cc70fdcab42a217473b9
