### ISSUE TITLE
Make delete button white and remove hardcoded positioning

### ISSUE THREAD

**Issue by EverettBerry** [kirbyk/donger-board#6]
Test on multiple devices

**Comment by nlarew** [comment]
Fixed up the color issue by changing the UIButton type for deleteButton from `let deleteButton = UIButton(type: .System)` to `let deleteButton = UIButton(type: UIButtonType.Custom)` in KeyboardViewController.swift

**Comment by nlarew** [comment]
55aa44c81bc9cf198aee7e9bf9daaf7dbb35ecc6
